apiVersion: v1
kind: Service
metadata:
  name: test-pipeline-service
spec:
  selector:
    app: test-pipeline
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-pipeline
spec:
  selector:
    matchLabels:
      app: test-pipeline
  replicas: 2
  template:
    metadata:
      labels:
        app: test-pipeline
    spec:
      containers:
      - name: test-pipeline
        image: test-pipeline:tagname
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
